{
  "openapi": "3.0.0",
  "info": {
    "title": "02. YakusesProjectBackend(Augst24)",
    "description": "# ðŸ“„ Get started here",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://127.0.0.1:5000"
    },
    {
      "url": "http://{{yakuse-production}}"
    },
    {
      "url": "https://yakusesprojectbackend-production.up.railway.app"
    }
  ],
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer"
      },
      "apikeyAuth": {
        "type": "http",
        "scheme": "apikey"
      }
    }
  },
  "security": [
    {
      "apikeyAuth": []
    }
  ],
  "tags": [
    {
      "name": "User",
      "description": "The `/me` endpoints let you manage information about the authenticated user."
    },
    {
      "name": "User > Post"
    },
    {
      "name": "User > Get"
    }
  ],
  "paths": {
    "/user/register": {
      "post": {
        "tags": [
          "User > Post"
        ],
        "summary": "post register user member",
        "description": "Gets information about the authenticated user.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "username": "usertester",
                  "fullname": "John",
                  "email": "testeruser@example.com",
                  "password": "password"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "CREATED",
            "headers": {
              "Server": {
                "schema": {
                  "type": "string",
                  "example": "Werkzeug/3.0.3 Python/3.11.8"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Thu, 08 Aug 2024 04:49:41 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "318"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "close"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "about_me": null,
                  "address": null,
                  "created_at": "2024-08-08T04:49:37.509030+00:00",
                  "email": "testeruser@example.com",
                  "fullname": "John",
                  "id": "5c433dbe-6ce2-4188-96ce-a8ed4159fcad",
                  "phone": null,
                  "role": "member",
                  "updated_at": "2024-08-08T04:49:37.509030+00:00",
                  "username": "usertester"
                }
              }
            }
          }
        }
      }
    },
    "/user/login": {
      "post": {
        "tags": [
          "User > Post"
        ],
        "summary": "post user login (local) member",
        "description": "Gets information about the authenticated user.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "testeruser@example.com",
                  "password": "password"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Server": {
                "schema": {
                  "type": "string",
                  "example": "Werkzeug/3.0.3 Python/3.11.8"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Thu, 08 Aug 2024 04:50:44 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "397"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "close"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMzA5MjY0NCwianRpIjoiYzkzNTIwNTItNmE2ZC00NmYwLTliZmMtNGRlZjBkNjQ3NGM3IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjVjNDMzZGJlLTZjZTItNDE4OC05NmNlLWE4ZWQ0MTU5ZmNhZCIsIm5iZiI6MTcyMzA5MjY0NCwiY3NyZiI6ImMyMjZlMWY4LTU5ZGYtNDI1Ni04ZjJjLTA4OTg1YWM5MGVhZCIsImV4cCI6MTcyMzA5MzU0NH0.SnKOq0TCxmWQXi7JYRWOGoWn8awJw43PsQmbZMiwyEA"
                }
              }
            }
          }
        }
      }
    },
    "/user/profile": {
      "get": {
        "tags": [
          "User > Get"
        ],
        "summary": "get user profile",
        "description": "Gets information about the authenticated user.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Server": {
                "schema": {
                  "type": "string",
                  "example": "Werkzeug/3.0.3 Python/3.11.8"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Thu, 08 Aug 2024 04:53:07 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "438"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "close"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "examples": {
                  "example-0": {
                    "summary": "get user profile",
                    "value": {
                      "my_profile": {
                        "about_me": null,
                        "address": null,
                        "created_at": "2024-08-08T04:49:37.509030+00:00",
                        "email": "testeruser@example.com",
                        "fullname": "John",
                        "id": "5c433dbe-6ce2-4188-96ce-a8ed4159fcad",
                        "phone": null,
                        "role": "member",
                        "updated_at": "2024-08-08T04:49:37.509030+00:00",
                        "username": "usertester"
                      },
                      "password": "$2b$12$TDXrTgXHACUVhr7uRHNXNOxrh0P4NxieNq6Bovk.G1xQFZJD8oxQu"
                    }
                  },
                  "example-1": {
                    "summary": "get user profile",
                    "value": {
                      "my_profile": {
                        "about_me": [
                          "testeruser",
                          "is robot tester"
                        ],
                        "address": "jln.testeruser",
                        "created_at": "2024-08-08T04:49:37.509030+00:00",
                        "email": "testeruser@example.com",
                        "fullname": "John",
                        "id": "5c433dbe-6ce2-4188-96ce-a8ed4159fcad",
                        "phone": "1234567890",
                        "role": "member",
                        "updated_at": "2024-08-08T15:18:09.562172+00:00",
                        "username": "usertester"
                      },
                      "password": "$2b$12$TDXrTgXHACUVhr7uRHNXNOxrh0P4NxieNq6Bovk.G1xQFZJD8oxQu"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/user/edit": {
      "put": {
        "tags": [
          "User"
        ],
        "summary": "Edit user profile",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "phone": "1234567890",
                  "address": "jln.testeruser",
                  "about_me": [
                    "testeruser",
                    "is robot tester"
                  ]
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Server": {
                "schema": {
                  "type": "string",
                  "example": "Werkzeug/3.0.3 Python/3.11.8"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Thu, 08 Aug 2024 15:18:11 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "379"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "close"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "about_me": [
                    "testeruser",
                    "is robot tester"
                  ],
                  "address": "jln.testeruser",
                  "created_at": "2024-08-08T04:49:37.509030+00:00",
                  "email": "testeruser@example.com",
                  "fullname": "John",
                  "id": "5c433dbe-6ce2-4188-96ce-a8ed4159fcad",
                  "phone": "1234567890",
                  "role": "member",
                  "updated_at": "2024-08-08T15:18:09.562172+00:00",
                  "username": "usertester"
                }
              }
            }
          }
        }
      }
    },
    "/": {
      "get": {
        "tags": [
          "default"
        ],
        "summary": "Home-Production",
        "description": "Gets information about the authenticated user.",
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              },
              "Content-Encoding": {
                "schema": {
                  "type": "string",
                  "example": "gzip"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Wed, 14 Aug 2024 04:01:08 GMT"
                }
              },
              "Server": {
                "schema": {
                  "type": "string",
                  "example": "railway-edge"
                }
              },
              "X-Request-Id": {
                "schema": {
                  "type": "string",
                  "example": "foakQcpIQ9KbPPLuTRjfag_3176973899"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "86"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Access to Yakuses Backend-API is available !!!"
                }
              }
            }
          }
        }
      }
    }
  }
}